### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [rhirst/tc359_project9#1]
It looks like this repo might not be completely up-to-date with the Heroku app. Specifically, I'm looking at [`static.css`](https://github.com/rhirst/tc359_project9/blob/master/app/assets/stylesheets/static.css) and some errors that this would cause, preventing it from even deploying to Heroku. Does that make sense? It's probably as simple as just doing another `git push origin master`.

**Comment by rhirst** [comment]
It looks like that was the case, I just updated it so it should all be good now.

**Comment by chrisvfritz** [comment]
:+1: Looking good!
